LOAD DATA INFILE 'C:\Users\das\Downloads\sec_bhavdata_full.csv'
BADFILE 'C:\Users\das\Downloads\sec_bhavdata_full.bad'
DISCARDFILE 'C:\Users\das\Downloads\sec_bhavdata_full.dsc'
APPEND INTO TABLE daily_nse_all FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(SYMBOL, SERIES, DATE1 date 'dd-mon-yyyy', PREV_CLOSE, OPEN_PRICE, HIGH_PRICE, LOW_PRICE, LAST_PRICE, CLOSE_PRICE, AVG_PRICE, TTL_TRD_QNTY, TURNOVER_LACS, NO_OF_TRADES, DELIV_QTY, DELIV_PER)
