C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	JSWSTEEL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	JUBLFOOD
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	JUSTDIAL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	KOTAKBANK
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote_ltfin.py
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	LT
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	LICHSGFIN
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	LUPIN
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote_mahfin.py
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	MGL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote_mahindra.py
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	MANAPPURAM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	MARICO
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	MARUTI
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	MFSL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	MINDTREE
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	MOTHERSUMI
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	MRF
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	MUTHOOTFIN
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	NATIONALUM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	NCC
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	NESTLEIND
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	NIITTECH
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	NMDC
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	NTPC
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	ONGC
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	OIL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	PAGEIND      
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	PETRONET
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	PIDILITIND
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	PEL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	PFC
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	POWERGRID
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	PNB
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	PVR
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	RBLBANK
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	RELIANCE
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	RECLTD
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	SHREECEM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	SRTRANSFIN
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	SIEMENS
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	SRF
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	SBIN
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	SBILIFE
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	SAIL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	SUNPHARMA
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	SUNTV
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	TATACONSUM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	TATACHEM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	TCS
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	TATACONSUM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py        TATAMOTORS
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	TATAPOWER
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	TATASTEEL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	TECHM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	RAMCOCEM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	TITAN
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	TORNTPHARM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	TORNTPOWER
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	TVSMOTOR
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	UJJIVAN
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	ULTRACEMCO
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	UBL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	MCDOWELL-N
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	UPL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py        VEDL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	VOLTAS
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	WIPRO
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py 	YESBANK
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py	ZEEL
