C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py UJJIVAN
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py ADANIPOWER
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py GODREJCP
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py NHPC
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py SIEMENS
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py TATACHEM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py CANFINHOME
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py IDFCFIRSTB
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py INDIACEM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py CESC
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote_mahfin.py
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py MCX
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py MRPL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py PEL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py SOUTHBANK
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py SYNDIBANK
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py TATAELXSI
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py BATAINDIA
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py IFCI
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py JSWSTEEL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py RELINFRA
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py TATACOMM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py TVSMOTOR
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py SRF
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py PVR
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py BOSCHLTD
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py COLPAL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py GSFC
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py IDFC
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py INFIBEAM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py JUSTDIAL
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py KTKBANK
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py MANAPPURAM
C:\Migration\python\python  C:\Migration\python\Scripts\get_price_quote.py MGL
